spring:
  application:
    name: search-web
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 18088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true



