server:
  port: 18090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.128:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    port: 6379
    host: 192.168.110.128
  main:
    allow-bean-definition-overriding: true


  rabbitmq:
    host: 192.168.110.128
    port: 5672



eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE

#位置支付交换机和队列
mq:
  pay:
    queue:
      order: queue.order

